### ISSUE TITLE
Could you upload the "val.txt" and "imagenet.pickle" files?

### ISSUE THREAD

**Issue by zhangdong1992** [labsix/limited-blackbox-attacks#11]

**Comment by maithal** [comment]
Did you get the val.txt file?

**Comment by zhangdong1992** [comment]
yes

**Comment by maithal** [comment]
Can you please provide val.txt?

It will be very helpful.

**Comment by anishathalye** [comment]
It's a standard file from the ImageNet dataset. If it's helpful to you to have it separately, here you go: [val.txt](https://github.com/labsix/limited-blackbox-attacks/files/5100014/val.txt)

**Comment by maithal** [comment]
Thank you so much! I highly appreciate your help.
