### ISSUE TITLE
 The system cannot find the path specified

### ISSUE THREAD

**Issue by maithal** [labsix/limited-blackbox-attacks#17]
Hi, I am trying to run the attack method and I am facing the problem for dataset not being determined/found. I constantly get the following error.

Traceback (most recent call last):
  File "C:/Users/Documents/NES_Evaluation/main.py", line 93, in <module>
    main()
  File "C:/Users/Documents/NES_Evaluation/main.py", line 86, in main
    attacks.main(args, gpus)
  File "C:\Users\Documents\NES_Evaluation\attacks.py", line 32, in main
    x, y = get_image(args.img_index, IMAGENET_PATH)
  File "C:\Users\\Documents\NES_Evaluation\tools\utils.py", line 52, in get_image
    image_paths = sorted([os.path.join(data_path, i) for i in os.listdir(data_path)])
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Documents\\NES_Evaluation\\imagenet\\data.npy\\val'
{"samples_per_draw": 50, "batch_size": 50, "target_class": null, "orig_class": null, "sigma": 0.001, "epsilon": 0.05, "img_path": null, "img_index": 1, "out_dir": "Results", "log_iters": 1, "restore": null, "momentum": 0.9, "max_queries": 10000, "save_iters": 50, "plateau_drop": 2.0, "min_lr_ratio": 200, "plateau_length": 5, "gpus": 1, "imagenet_path": null, "visualize": false, "max_lr": 0.01, "min_lr": 5e-05, "top_k": -1, "adv_thresh": -1.0, "label_only": false, "zero_iters": 100, "label_only_sigma": 0.001, "starting_eps": 1.0, "starting_delta_eps": 0.5, "min_delta_eps": 0.1, "conservative": 2}

Process finished with exit code 1

Any help will be highly appreciated.

Thanks!

**Comment by Darylnn** [comment]
Can I ask which if you used the downsampled ImageNet dataset or the original ImageNet LSVRC 2012 Training Set and Validation Set? Because I am also encountering this problem now and I have no idea how to solve this

**Comment by maithal** [comment]
I didn't change the image dataset. You can find the dataset and create a folder and add the path of that folder. Sometime the issue is with the path name and check the labels text file is present in your image folder.
