### ISSUE TITLE
About the ImageNet data

### ISSUE THREAD

**Issue by JFChi** [labsix/limited-blackbox-attacks#2]
Hi,

Could you please share the exact ImageNet dataset folder(or download link or pickle file) you used in the experiments? Since in the utils.py, val.txt is mentioned. I think this is somehow different from the original ImageNet data.

**Comment by anishathalye** [comment]
We downloaded the ImageNet dataset from here: http://academictorrents.com/collection/imagenet-2012.

The validation set in particular can be found [here](http://academictorrents.com/details/5d6d0df7ed81efd49ca99ea4737e0ae5e3a5f2e5).
