### ISSUE TITLE
Question about number of queries

### ISSUE THREAD

**Issue by dongyp13** [labsix/limited-blackbox-attacks#3]
Hi,

In label-only attack, the queries are increased by 'samples_per_draw' in each iteration. Do you count the queries for evaluating the loss?

**Comment by anishathalye** [comment]
We take the mean (see https://github.com/labsix/limited-blackbox-attacks/blob/master/attacks.py#L158), so increasing samples_per_draw doesn't affect the expectation of the loss.

**Comment by dongyp13** [comment]
I mean the calculation of the number of queries [().](https://github.com/labsix/limited-blackbox-attacks/blob/master/attacks.py#L252) I think there are additional queries for estimating the loss in the label-only setting [().](https://github.com/labsix/limited-blackbox-attacks/blob/master/attacks.py#L110).

**Comment by anishathalye** [comment]
Yes, it is taken into account when measuring the number of queries. `#queries = samples_per_step * iterations`

**Comment by dongyp13** [comment]
I'm a little bit confusing. In the label-only attack, you use `samples_per_step` to estimate the gradient direction, but in each sample, you also use `zero_iters` to estimate the loss [(https://github.com/labsix/limited-blackbox-attacks/blob/master/attacks.py#L104-117)](https://github.com/labsix/limited-blackbox-attacks/blob/master/attacks.py#L104-117). I think the number of queries should by updated as `num_queries += args.samples_per_draw * zero_iters`.

**Comment by andrewilyas** [comment]
Yes, you are correct! In the paper we account for this manually by multiplying our final result by zero_iters. Will fix this soon and close.

**Comment by dongyp13** [comment]
Thanks for your reply.

**Comment by andrewilyas** [comment]
This has been fixed.
