### ISSUE TITLE
Question on hyperparameter

### ISSUE THREAD

**Issue by drillermoon** [labsix/limited-blackbox-attacks#8]
Hi.
In the paper, it was said that you used momentum-based pgd in query-limited attack, but the momentum is set to zero in the code.
Is there any reason why you set it to zero?(Actually, I found that increasing momentum gives better success rate and query efficiency.)
Thank you.

**Comment by anishathalye** [comment]
We used momentum for the experiments in the paper.

As in #7, I think this is an error that was made when the code was refactored for open-sourcing.

Thank you for pointing this out. It has been fixed in 47f7b0739933ca1b5d2c21606016276dc55200fc.

**Comment by drillermoon** [comment]
Thanks a lot!
