### ISSUE TITLE
Porting to models trained on CIFAR-10

### ISSUE THREAD

**Issue by seansaito** [labsix/limited-blackbox-attacks#9]
Hi,

Thanks for open-sourcing this! I'm wondering whether you have tried attacking models trained on CIFAR-10; if so, what should I set the hyperparameters to? I'm only using the label-only attack for now.

The ones provided by `label-only.sh` are not that successful (either the `goal_epsilon` cannot be reached or `padv != 1`), but I understand that this is meant for ImageNet models.

**Comment by anishathalye** [comment]
It's expected that you'll need different attack hyperparameters for a CIFAR-10 model. We recommend that you try a grid search for parameters.
